' SyntaxParser.vb
'
' THIS FILE HAS BEEN GENERATED AUTOMATICALLY. DO NOT EDIT!

Imports System.IO

Imports Core.Library

'''<remarks>A token stream parser.</remarks>
Public Class SyntaxParser
    Inherits RecursiveDescentParser

    '''<summary>An enumeration with the generated production node
    '''identity constants.</summary>

    '''<summary>Creates a new parser with a default analyzer.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Public Sub New(ByVal input As TextReader)
        MyBase.New(input)
        CreatePatterns()
    End Sub

    '''<summary>Creates a new parser.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<param name='analyzer'>the analyzer to parse with</param>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Public Sub New(ByVal input As TextReader, ByVal analyzer As SyntaxAnalyzer)
        MyBase.New(input, analyzer)
        CreatePatterns()
    End Sub

    '''<summary>Creates a new tokenizer for this parser. Can be overridden
    '''by a subclass to provide a custom implementation.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<returns>the tokenizer created</returns>
    '''
    '''<exception cref='ParserCreationException'>if the tokenizer
    '''couldn't be initialized correctly</exception>
    Protected Overrides Function NewTokenizer(ByVal input As TextReader) As Tokenizer
        Return New SyntaxTokenizer(input)
    End Function

    '''<summary>Initializes the parser by creating all the production
    '''patterns.</summary>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Private Sub CreatePatterns()
        Dim pattern As ProductionPattern
        Dim alt As ProductionPatternAlternative

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_PROGRAM), "prod_program")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ENTRANCE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_GLOBAL_DEC), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.MANE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MANE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SUB_FUNCTION), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.EXIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COMMENT), "prod_comment")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMSYM), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.COMMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_GLOBAL_DEC), "prod_global_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_STORK_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONST_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAR_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.VIPER), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_NAME), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_PARAM), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VAR_DEC), "prod_var_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_VAR), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_VAR), "prod_func_var")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_PARAM), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_IDENT_VAR), "prod_ident_var")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_DTYPE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_DTYPE), "prod_dtype")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCK), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLING), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.BULL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_NEXT2VAR), "prod_next2var")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARRAY1D), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_NEXT2VAR_TAIL), "prod_next2var_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VAL), "prod_val")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL2), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VAL1), "prod_val1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VAL2), "prod_val2")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_BUL_LIT), "prod_bulLit")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.TRUE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.FALSE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARRAY1D), "prod_array1D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM1D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEM1D_NEXT), "prod_elem1D_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM2D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEM1D_LIST), "prod_elem1D_list")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEMLIST1D_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEMLIST1D_TAIL), "prod_elemlist1D_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEMLIST1D_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEM2D_NEXT), "prod_elem2D_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM2D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEM2D_LIST), "prod_elem2D_list")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM2D_LIST_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ELEM2D_LIST_TAIL), "prod_elem2D_list_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SIZE), "prod_size")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_CONST_DEC), "prod_const_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.LET), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_IDENT_VAR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONST_NEXT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_CONST_NEXT), "prod_const_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONST_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_NAME), "prod_func_name")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_PARAM), "prod_param")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_DTYPE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_PARAM2), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_PARAM2), "prod_param2")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_DTYPE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_PARAM2), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_STORK_DEC), "prod_stork_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STORK), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STORK_ELEM), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTISTORK_ELEM), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_OBJ_DEC), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_STORK_ELEM), "prod_stork_elem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_VARDEC), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MULTI_VARDEC), "prod_multi_vardec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_VARDEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MULTISTORK_ELEM), "prod_multistork_elem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_STORK_ELEM), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_OBJ_DEC), "prod_obj_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_VARDEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MANE), "prod_mane")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOCAL_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOCAL_DEC), "prod_local_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT2VAR), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOCAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_STATEMENT), "prod_statement")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_INPUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_OUTPUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONDITIONAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ITERATIVE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATE_NEXT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_CLRSCR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_STATE_NEXT), "prod_state_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ASSIGN1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT_FIG), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ASSIGN1), "prod_assign1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ASSIGN_TAIL), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT_FIG), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ASSIGN_TAIL), "prod_assign_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_NEXT_FIG), "prod_next_fig")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_NEXT), "prod_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CON), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_CALL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_EXPONENT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SCAN_NEXT), "prod_scan_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VALUE_DL), "prod_valueDL")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FIG), "prod_fig")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_CALL), "prod_func_call")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARGS1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_NEXT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARGS1), "prod_args1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARG_IN), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARGS_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARGS_TAIL), "prod_args_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARG_IN), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARGS_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARG_IN), "prod_arg_in")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_NEXT), "prod_func_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC), "prod_func")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_NEXT_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_EQTAIL), "prod_math_eqtail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL2), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_EQTAIL1), "prod_math_eqtail1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATHEQ_NEXT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_EXPONENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_EQTAIL2), "prod_math_eqtail2")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_EXPONENT), "prod_exponent")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EXP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_TAIL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_TAIL), "prod_math_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_OP), "prod_math_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ADD), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SUB), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.MUL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DIV), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.MOD), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_FIG), "prod_math_fig")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATH_FIG1), "prod_math_fig1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MATHEQ_NEXT), "prod_matheq_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNCTION_CALL), "prod_function_call")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARGS1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_CLRSCR), "prod_clrscr")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.WIPE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_INPUT), "prod_input")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ZOOIN), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_INPUT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SCAN_FIG), "prod_scan_fig")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_STORK_ACCESS1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MULTI_INPUT), "prod_multi_input")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CDA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_INPUT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARR1D), "prod_arr1D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARR2D), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ARR2D), "prod_arr2D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_STORK_ACCESS1), "prod_stork_access1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CONC), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_OUTPUT), "prod_output")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ZOOUT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_OUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_OUTPUT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_OUT), "prod_out")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_OUTPUT_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_OUTPUT_NEXT), "prod_output_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_EQTAIL2), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_CALL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MULTI_OUTPUT), "prod_multi_output")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ODA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_OUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTI_OUTPUT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_CONDITIONAL), "prod_conditional")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.IF), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONDI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EELSIF), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EELS), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SWASP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SWASP_CASE), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_DEFAULT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_CONDI), "prod_condi")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EXC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_NOT_FIG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_NOT_FIG), "prod_not_fig")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COND_EXPR), "prod_cond_expr")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_EXPR), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COND_TAIL), "prod_cond_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOG_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_REL_EXPR), "prod_rel_expr")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_EXPRESSION), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_RELEX_TAIL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_RELEX_TAIL), "prod_relex_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_OP1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_EXPRESSION), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_OP2), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_FIG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_EXPRESSION), "prod_expression")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_EXPR_NEXT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_EXPR_NEXT), "prod_expr_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_REL_OP1), "prod_rel_op1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OA), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CA), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OAE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CAE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_REL_OP2), "prod_rel_op2")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_REL_FIG), "prod_rel_fig")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NULL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SCAN_FIG), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOG_EXPR), "prod_log_expr")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOG_OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOG_EXPR_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOG_EXPR_NEXT), "prod_log_expr_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOG_OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOG_EXPR_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOG_OP), "prod_log_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DAND), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DOR), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COND_EELSIF), "prod_cond_eelsif")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EELSIF), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONDI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COND_EELSIF), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COND_EELS), "prod_cond_eels")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EELS), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SWASP_CASE), "prod_swasp_case")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CHAMOIS), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_TERM_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.SC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMITE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SWASP_CASE1), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SWASP_CASE1), "prod_swasp_case1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_SWASP_CASE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_TERM_EXPR), "prod_term_expr")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_DEFAULT), "prod_default")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SEAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_ITERATIVE), "prod_iterative")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.WHALE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONDI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG2), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DO), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.WHALE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_CONDI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.FUR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_EXPR1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG2), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOOP_FIG1), "prod_loop_fig1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_REL_EXPR1), "prod_rel_expr1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_REL_OP1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARG_IN), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_LOOP_FIG2), "prod_loop_fig2")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_INCREM_DECREM), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_INCREM_DECREM), "prod_increm_decrem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_UNARY_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAR), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_UNARY_OP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_VAR), "prod_var")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_UNARY_OP), "prod_unary_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.INCRE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DECRE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_SUB_FUNCTION), "prod_sub_function")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_DTYPE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_NAME), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_ARGS), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_INSIDE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.HOP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_RESULT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SUB_FUNCTION), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.VIPER), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_ARGS), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_INSIDE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_SUB_FUNCTION), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_INSIDE), "prod_func_inside")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOCAL_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_STATEMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FUNC_ARGS), "prod_func_args")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MULTIFUNC_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MULTIFUNC_ARGS), "prod_multifunc_args")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FUNC_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_RESULT), "prod_result")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_VAL2), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_RESULT_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FIG_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_FIG_TAIL), "prod_fig_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FIG_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_RESULT_TAIL), "prod_result_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARGS1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_LOOP_FIG1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_FIG_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.PROD_ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)
    End Sub
End Class
