' SyntaxParser.vb
'
' THIS FILE HAS BEEN GENERATED AUTOMATICALLY. DO NOT EDIT!

Imports System.IO

Imports PerCederberg.Grammatica.Runtime

'''<remarks>A token stream parser.</remarks>
Public Class SyntaxParser
    Inherits RecursiveDescentParser

    '''<summary>An enumeration with the generated production node
    '''identity constants.</summary>


    '''<summary>Creates a new parser with a default analyzer.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Public Sub New(ByVal input As TextReader)
        MyBase.New(input)
        CreatePatterns()
    End Sub

    '''<summary>Creates a new parser.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<param name='analyzer'>the analyzer to parse with</param>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Public Sub New(ByVal input As TextReader, ByVal analyzer As SyntaxAnalyzer)
        MyBase.New(input, analyzer)
        CreatePatterns()
    End Sub

    '''<summary>Creates a new tokenizer for this parser. Can be overridden
    '''by a subclass to provide a custom implementation.</summary>
    '''
    '''<param name='input'>the input stream to read from</param>
    '''
    '''<returns>the tokenizer created</returns>
    '''
    '''<exception cref='ParserCreationException'>if the tokenizer
    '''couldn't be initialized correctly</exception>
    Protected Overrides Function NewTokenizer(ByVal input As TextReader) As Tokenizer
        Return New SyntaxTokenizer(input)
    End Function

    '''<summary>Initializes the parser by creating all the production
    '''patterns.</summary>
    '''
    '''<exception cref='ParserCreationException'>if the parser
    '''couldn't be initialized correctly</exception>
    Private Sub CreatePatterns()
        Dim pattern As ProductionPattern
        Dim alt As ProductionPatternAlternative

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROGRAM), "program")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ENTRANCE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_DEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_FUNCDEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_MANE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SUB_FUNCTION), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.EXIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_COMMENT), "prod_comment")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMSYM), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.COMMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.GLOBAL_DEC), "global_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAR_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_DEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.CONST_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STORK_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.GLOBAL_FUNCDEC), "global_funcdec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.FUNC_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.GLOBAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.VAR_DEC), "var_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2_VAR), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.IDENT_VAR), "ident_var")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.DTYPE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.DTYPE), "dtype")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCK), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLING), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.BULL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.NEXT2_VAR), "next2_var")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2_VAR), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2VAR_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARRAY1D), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2VAR_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.NEXT2VAR_TAIL), "next2var_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARRAY2D), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2VAR_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEXT2_VAR), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.VAL), "val")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.BUL_LIT), "bulLit")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.TRUE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.FALSE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARRAY1D), "array1D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM1D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ELEM1D_NEXT), "elem1D_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ELEM1D_LIST), "elem1D_list")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEMLIST1D_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ELEMLIST1D_TAIL), "elemlist1D_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEMLIST1D_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARRAY2D), "array2D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM2D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ELEM2D_NEXT), "elem2D_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM2D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM2D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ELEM2D_LIST), "elem2D_list")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM1D_LIST), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ELEM2D_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SIZE), "size")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.CONST_DEC), "const_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.LET), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.IDENT_VAR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.CONST_NEXT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.CONST_NEXT), "const_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.CONST_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.FUNC_DEC), "func_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.DTYPE1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PARAM), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.DTYPE1), "dtype1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.VIPER), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.DTYPE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PARAM), "param")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.DTYPE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_PARAM), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTI_PARAM), "multi_param")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PARAM), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STORK_DEC), "stork_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STORK), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STORK_ELEM), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTISTORK_ELEM), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.OBJ_DEC), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STORK_ELEM), "stork_elem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_VARDEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTI_VARDEC), "multi_vardec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_VARDEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTISTORK_ELEM), "multistork_elem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STORK_ELEM), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.OBJ_DEC), "obj_dec")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_VARDEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.PROD_MANE), "prod_mane")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.MANE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOCAL_DEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.RETURN), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOCAL_DEC), "local_dec")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAR_DEC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOCAL_DEC), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STATEMENT), "statement")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.INPUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.OUTPUT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.CLRSCR), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.MATH_EQ), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.CONDITIONAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ITERATIVE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.CLRSCR), "clrscr")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.WIPE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STATEMENT1), "statement1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.FUNCTION_CALL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STATEMENT_TAIL), "statement_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.INPUT), "input")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ZOOIN), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SCAN_FIG), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_INPUT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SCAN_FIG), "scan_fig")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STORK_ACCESS1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTI_INPUT), "multi_input")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CDP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SCAN_FIG), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_INPUT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARR1D), "arr1D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARR2D), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARR2D), "arr2D")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.STORK_ACCESS1), "stork_access1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CONC), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.OUTPUT), "output")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ZOOUT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.OUTPUT_NEXT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_OUTPUT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.OUTPUT_NEXT), "output_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SCAN_FIG1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_EQTAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTI_OUTPUT), "multi_output")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ODP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.OUTPUT_NEXT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_OUTPUT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SCAN_FIG1), "scan_fig1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.STORK_ACCESS1), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATH_EQ), "math_eq")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_EQTAIL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATH_EQTAIL), "math_eqtail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.NEGATE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_TAIL), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATHEQ_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CON), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CON), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.STARLING), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.MATH_ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATHEQ_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATH_TAIL), "math_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATH_OP), "math_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ADD), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SUB), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.MUL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DIV), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.MOD), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EXP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATH_ID), "math_id")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.NEGATE), "negate")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MATHEQ_NEXT), "matheq_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NEGATE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATH_ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MATHEQ_NEXT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.CONDITIONAL), "conditional")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.IF), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EELSIF), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SWASP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SWASP_CASE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.DEFAULT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.COND_EXPR), "cond_expr")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.REL_EXPR1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.LOG_EXPR), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.REL_EXPR1), "rel_expr1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.RELEX_TAIL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.RELEX_TAIL), "relex_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.REL_OP1), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARITHMETIC), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.REL_OP2), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.REL_FIG), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARITHMETIC), "arithmetic")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.EXPRESSION), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARITHMETIC_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARITHMETIC_TAIL), "arithmetic_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.MATH_OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.EXPRESSION), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARITHMETIC_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.EXPRESSION), "expression")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.NEGATE), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.EXPR_NEXT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.EXPR_NEXT), "expr_next")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DUCKLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.REL_OP1), "rel_op1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OA), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CA), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OAE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CAE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.REL_OP2), "rel_op2")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.REL_FIG), "rel_fig")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.SCAN_FIG1), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOG_EXPR), "log_expr")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EXC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.NOT_FIG), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOG_OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOG_EXPR_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.NOT_FIG), "not_fig")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.BUL_LIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOG_EXPR_NEXT), "log_expr_next")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.LOG_OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOG_EXPR_NEXT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOG_OP), "log_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DAND), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DOR), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.COND_EELSIF), "cond_eelsif")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EELSIF), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EELSIF), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EELS), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.COND_EELS), "cond_eels")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.EELS), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SWASP_CASE), "swasp_case")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.CHAMOIS), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.TERM_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.SC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMITE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SWASP_CASE1), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SWASP_CASE1), "swasp_case1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.SWASP_CASE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.TERM_EXPR), "term_expr")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.STARLIT), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.DEFAULT), "default")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.SEAL), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ITERATIVE), "iterative")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.WHALE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOOP_FIG2), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DO), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.WHALE), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.COND_EXPR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.FUR), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.EQUAL), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOOP_FIG1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.REL_EXPR1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOOP_FIG2), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOOP_FIG1), "loop_fig1")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.NEWTLIT), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.LOOP_FIG2), "loop_fig2")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.INCREM_DECREM), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.INCREM_DECREM), "increm_decrem")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.UNARY_OP), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.UNARY_OP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.UNARY_OP), "unary_op")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.INCRE), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.DECRE), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.FUNCTION_CALL), "function_call")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARGS1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARGS1), "args1")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARGS2), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARGS2), "args2")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARGS_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ARGS_TAIL), "args_tail")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.SIZE), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARR2D), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTI_ARGS), "multi_args")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARGS2), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTI_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.SUB_FUNCTION), "sub_function")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.DTYPE1), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.AT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.FUNC_ARGS), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.ODC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.LOCAL_DEC), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.STATEMENT1), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.RETURN), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CDC), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.FUNC_ARGS), "func_args")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.IDENT_VAR), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.FUNC_TAIL), 0, 1)
        alt.AddProduction(CInt(SyntaxConstants.MULTIFUNC_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.FUNC_TAIL), "func_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ONE_ARRAY), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.ONE_ARRAY), "one_array")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.TWO_ARRAY), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.TWO_ARRAY), "two_array")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OB), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.CB), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.MULTIFUNC_ARGS), "multifunc_args")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.COMMA), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.FUNC_ARGS), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.RETURN), "return")
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.HOP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.RESULT), 1, 1)
        alt.AddToken(CInt(SyntaxConstants.TERMI), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.PROD_COMMENT), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.RESULT), "result")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.VAL), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.ID), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.RESULT_TAIL), 0, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)

        pattern = New ProductionPattern(CInt(SyntaxConstants.RESULT_TAIL), "result_tail")
        alt = New ProductionPatternAlternative()
        alt.AddProduction(CInt(SyntaxConstants.ARR1D), 1, 1)
        pattern.AddAlternative(alt)
        alt = New ProductionPatternAlternative()
        alt.AddToken(CInt(SyntaxConstants.OP), 1, 1)
        alt.AddProduction(CInt(SyntaxConstants.ARGS1), 0, 1)
        alt.AddToken(CInt(SyntaxConstants.CP), 1, 1)
        pattern.AddAlternative(alt)
        AddPattern(pattern)
    End Sub
End Class
